export const ROUTE_PATHS = {
  home: "/",
  login: "/login",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  orders: "/orders",
  liveOrders: "/orders/live",
  pendingOrders: "/orders/pending",
  orderHistory: "/orders/history",
  monitoring: "/monitoring",
  mojro: "/monitoring/mojro",
  cef: "/monitoring/cef",
  reports: "/reports",
  profile: "/profile",
  createUser: "/users/new",
  unauthorized: "/unauthorized",
} as const;
